/**
 * @file ui_menu.h
 *
 * @brief Header file for the ui_menu class
 *
 * The ui_menu class represents the UI for the menu dialog.
 * It is part of the user interface generated by Qt Designer.
 *
 * @author Adrian Horvath (xhorva14)
 */

#ifndef UI_MENU_H
#define UI_MENU_H

#include <QDialog>

namespace Ui {
class ui_menu;
}

class ui_menu : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Constructs a ui_menu instance.
     * @param parent The parent QWidget.
     */
    explicit ui_menu(QWidget *parent = nullptr);

    /**
     * @brief Destroys the ui_menu instance.
     */
    ~ui_menu();

private:
    Ui::ui_menu *ui;
};

#endif // UI_MENU_H
